/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bmdrc.basicchemistry.windows;

import java.awt.BorderLayout;
import java.io.File;
import java.io.Serializable;
import org.bmdrc.basicchemistry.panel.Molecule3dStructurePanel;
import org.bmdrc.basicchemistry.windows.interfaces.IMoleculeViewer;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.bmdrc.basicchemistry.windows//MoleculeStructureViewer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "MoleculeStructureViewerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.bmdrc.basicchemistry.windows.MoleculeStructureViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_MoleculeStructureViewerAction",
        preferredID = "MoleculeStructureViewerTopComponent"
)
@Messages({
    "CTL_MoleculeStructureViewerAction=Molecule Viewer",
    "CTL_MoleculeStructureViewerTopComponent=Molecule Structure",
    "CTL_MoleculeStructureViewerTopComponentClassName=MoleculeStructureViewerTopComponent"
})
public final class MoleculeStructureViewerTopComponent extends TopComponent implements Serializable, IMoleculeViewer {

    private static final long serialVersionUID = -670684972601263651L;

    private MoleculeTableTopComponent itsTableComponent;
    private Molecule3dStructurePanel itsMoleculeStructurePanel;
    
    public MoleculeStructureViewerTopComponent() {
        this(Bundle.CTL_MoleculeStructureViewerTopComponent());
    }
    
    public MoleculeStructureViewerTopComponent(String theName) {
        initComponents();
        setName(theName);
    }
    
    public MoleculeStructureViewerTopComponent(File theMoleculeFile) {
        this(theMoleculeFile, theMoleculeFile.getName());
    }
    
    public MoleculeStructureViewerTopComponent(File theMoleculeFile, String theName) {
        this(null, theMoleculeFile, theName);
    }

    public MoleculeStructureViewerTopComponent(MoleculeTableTopComponent theTableTopComponent) {
        this(theTableTopComponent.getName());
        
        this.itsTableComponent = theTableTopComponent;
        this.itsMoleculeStructurePanel = new Molecule3dStructurePanel();
        
        this.add(this.itsMoleculeStructurePanel, BorderLayout.CENTER);
    }
    
    public MoleculeStructureViewerTopComponent(MoleculeTableTopComponent theTableTopComponent, File theMoleculeFile, String theName) {
        this(theName);
        
        this.itsTableComponent = theTableTopComponent;
        this.itsMoleculeStructurePanel = new Molecule3dStructurePanel(theMoleculeFile);
        
        this.add(this.itsMoleculeStructurePanel, BorderLayout.CENTER);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void viewMolecule(int theMoleculeIndex) {
        this.itsMoleculeStructurePanel.viewMolecule(theMoleculeIndex);
    }

    public void openFile(File theFile) {
        this.itsMoleculeStructurePanel.openFile(theFile);
    }
    
    public MoleculeTableTopComponent getTableComponent() {
        return itsTableComponent;
    }

    public void setTableComponent(MoleculeTableTopComponent theTableComponent) {
        this.itsTableComponent = theTableComponent;
    }
    
    
    @Override
    public void componentClosed() {
        if(this.itsTableComponent.isOpened()) {
            this.itsTableComponent.close();
        }
    }

    @Override
    protected void componentActivated() {
        if (!this.itsTableComponent.isShowing()) {
            this.itsTableComponent.requestActive();
        }
    }
    
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        // TODO read your settings according to their version
    }
}
