/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bmdrc.basicchemistry.windows;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.Box.Filler;
import javax.swing.JButton;
import org.bmdrc.basicchemistry.action.engine.PDBImporter;
import org.bmdrc.basicchemistry.reader.SDFReader;
import org.bmdrc.basicchemistry.table.MoleculeTable;
import org.bmdrc.ui.abstracts.Constant;
import org.bmdrc.ui.abstracts.WindowAdapter;
import org.bmdrc.ui.components.MemorialTextField;
import org.bmdrc.ui.util.TwoDimensionList;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.openide.util.Cancellable;
import org.openide.util.Exceptions;

/**
 *
 * @author Sungbo Hwang <sbhwang@bmdrc.org/tyamazaki@naver.com>
 */
public class PDBImportFrame extends javax.swing.JFrame {

    private MemorialTextField itsUrlTextField;
    private MemorialTextField itsPdbIdTextField;

    private final Integer FRAME_WIDTH = 400;
    private final Integer FRAME_HEIGHT = 170;

    /**
     * Creates new form PDBImportFrame
     */
    public PDBImportFrame() {
        initComponents();
        this.__initializeVariable();
        this.itsPdbIdTextField.requestFocus();
    }

    private void __initializeVariable() {
        this.__initializeMemorialTextField();
        this.__initializeListener();
    }

    private void __initializeMemorialTextField() {
        this.itsUrlTextField = new MemorialTextField(PDBImporter.URL_HEADER + PDBImporter.URL_TAIL);
        this.itsUrlTextField.setMinimumSize(new Dimension(0, 20));
        this.itsUrlTextField.setMaximumSize(new Dimension(Integer.MAX_VALUE, 20));
        this.itsUrlTextField.setPreferredSize(new Dimension(300, 20));

        this.itsPdbIdTextField = new MemorialTextField();
        this.itsPdbIdTextField.setMinimumSize(new Dimension(0, 20));
        this.itsPdbIdTextField.setMaximumSize(new Dimension(Integer.MAX_VALUE, 20));
        this.itsPdbIdTextField.setPreferredSize(new Dimension(300, 20));
        this.itsPdbIdTextField.addKeyListener(new PdbIdTextFieldActionListener(this));

        this.itsUrlTextFieldPanel.add(this.itsUrlTextField);
        this.itsUrlTextFieldPanel.add(new Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767)));

        this.itsPdbIdPanel.add(this.itsPdbIdTextField);
        this.itsPdbIdPanel.add(new Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767)));
    }

    private void __initializeListener() {
        this.itsOpenButton.addActionListener(new OpenButtonAcitionListener(this));
        this.itsExitButton.addActionListener(new ExitButtonActionListener(this));
    }

    private Point __setInitialLocation() {
        Dimension theScreenSize = Toolkit.getDefaultToolkit().getScreenSize();

        return new Point((theScreenSize.width - this.FRAME_WIDTH) / 2, (theScreenSize.height - this.FRAME_HEIGHT) / 2);
    }

    public MemorialTextField getUrlTextField() {
        return itsUrlTextField;
    }

    public MemorialTextField getPdbIdTextField() {
        return itsPdbIdTextField;
    }

    public JButton getOpenButton() {
        return itsOpenButton;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itsTotalPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        itsUrlLabelPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        itsUrlLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        itsUrlTextFieldPanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        itsPdbIdPanel = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        itsPdbIdLabel = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        itsButtonPanel = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        itsOpenButton = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        itsExitButton = new javax.swing.JButton();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(PDBImportFrame.class, "PDBImportFrame.title")); // NOI18N
        setAlwaysOnTop(true);
        setLocation(this.__setInitialLocation());
        setMaximumSize(new Dimension(this.FRAME_WIDTH, this.FRAME_HEIGHT));
        setMinimumSize(new Dimension(this.FRAME_WIDTH, this.FRAME_HEIGHT));
        setPreferredSize(new Dimension(this.FRAME_WIDTH, this.FRAME_HEIGHT));
        setResizable(false);

        itsTotalPanel.setBackground(new java.awt.Color(245, 245, 245));
        itsTotalPanel.setLayout(new javax.swing.BoxLayout(itsTotalPanel, javax.swing.BoxLayout.Y_AXIS));
        itsTotalPanel.add(filler1);

        itsUrlLabelPanel.setBackground(new java.awt.Color(245, 245, 245));
        itsUrlLabelPanel.setMaximumSize(new java.awt.Dimension(32767, 30));
        itsUrlLabelPanel.setMinimumSize(new java.awt.Dimension(160, 30));
        itsUrlLabelPanel.setLayout(new javax.swing.BoxLayout(itsUrlLabelPanel, javax.swing.BoxLayout.X_AXIS));
        itsUrlLabelPanel.add(filler3);

        org.openide.awt.Mnemonics.setLocalizedText(itsUrlLabel, org.openide.util.NbBundle.getMessage(PDBImportFrame.class, "PDBImportFrame.itsUrlLabel.text")); // NOI18N
        itsUrlLabelPanel.add(itsUrlLabel);

        itsTotalPanel.add(itsUrlLabelPanel);
        itsTotalPanel.add(filler2);

        itsUrlTextFieldPanel.setBackground(new java.awt.Color(245, 245, 245));
        itsUrlTextFieldPanel.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        itsUrlTextFieldPanel.setMinimumSize(new java.awt.Dimension(160, 30));
        itsUrlTextFieldPanel.setPreferredSize(new java.awt.Dimension(160, 30));
        itsUrlTextFieldPanel.setLayout(new javax.swing.BoxLayout(itsUrlTextFieldPanel, javax.swing.BoxLayout.X_AXIS));
        itsUrlTextFieldPanel.add(filler4);

        itsTotalPanel.add(itsUrlTextFieldPanel);
        itsTotalPanel.add(filler5);

        itsPdbIdPanel.setBackground(new java.awt.Color(245, 245, 245));
        itsPdbIdPanel.setMaximumSize(new java.awt.Dimension(32767, 30));
        itsPdbIdPanel.setMinimumSize(new java.awt.Dimension(160, 30));
        itsPdbIdPanel.setLayout(new javax.swing.BoxLayout(itsPdbIdPanel, javax.swing.BoxLayout.X_AXIS));
        itsPdbIdPanel.add(filler6);

        org.openide.awt.Mnemonics.setLocalizedText(itsPdbIdLabel, org.openide.util.NbBundle.getMessage(PDBImportFrame.class, "PDBImportFrame.itsPdbIdLabel.text")); // NOI18N
        itsPdbIdPanel.add(itsPdbIdLabel);
        itsPdbIdPanel.add(filler7);

        itsTotalPanel.add(itsPdbIdPanel);
        itsTotalPanel.add(filler8);

        itsButtonPanel.setBackground(new java.awt.Color(245, 245, 245));
        itsButtonPanel.setMaximumSize(new java.awt.Dimension(65660, 30));
        itsButtonPanel.setMinimumSize(new java.awt.Dimension(160, 30));
        itsButtonPanel.setPreferredSize(new java.awt.Dimension(160, 30));
        itsButtonPanel.setLayout(new javax.swing.BoxLayout(itsButtonPanel, javax.swing.BoxLayout.X_AXIS));
        itsButtonPanel.add(filler9);

        org.openide.awt.Mnemonics.setLocalizedText(itsOpenButton, org.openide.util.NbBundle.getMessage(PDBImportFrame.class, "PDBImportFrame.itsOpenButton.text")); // NOI18N
        itsButtonPanel.add(itsOpenButton);
        itsButtonPanel.add(filler10);

        org.openide.awt.Mnemonics.setLocalizedText(itsExitButton, org.openide.util.NbBundle.getMessage(PDBImportFrame.class, "PDBImportFrame.itsExitButton.text")); // NOI18N
        itsButtonPanel.add(itsExitButton);
        itsButtonPanel.add(filler11);

        itsTotalPanel.add(itsButtonPanel);

        getContentPane().add(itsTotalPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel itsButtonPanel;
    private javax.swing.JButton itsExitButton;
    private javax.swing.JButton itsOpenButton;
    private javax.swing.JLabel itsPdbIdLabel;
    private javax.swing.JPanel itsPdbIdPanel;
    private javax.swing.JPanel itsTotalPanel;
    private javax.swing.JLabel itsUrlLabel;
    private javax.swing.JPanel itsUrlLabelPanel;
    private javax.swing.JPanel itsUrlTextFieldPanel;
    // End of variables declaration//GEN-END:variables
    private class OpenButtonAcitionListener implements ActionListener {

        private PDBImportFrame itsFrame;
        private PDBImporter itsImporter;

        public OpenButtonAcitionListener(PDBImportFrame itsFrame) {
            this.itsFrame = itsFrame;
            this.itsImporter = new PDBImporter();
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            try {
                String thePdbId = this.itsFrame.getPdbIdTextField().getText();
                MoleculeTableTopComponent theTableTopComponent = new MoleculeTableTopComponent("PDB Importer (" + thePdbId + ")");
                MoleculeStructureViewerTopComponent theViewerTopComponent = new MoleculeStructureViewerTopComponent(theTableTopComponent);

                this.__setWindows(theTableTopComponent, theViewerTopComponent);
                
                this.itsFrame.dispose();

                this.itsImporter.setVariable(thePdbId, theTableTopComponent, theViewerTopComponent);
                this.itsImporter.actionPerformed(ae);
            } catch (Exception ex) {
                Exceptions.printStackTrace(ex);
            }
        }

        private void __setWindows(MoleculeTableTopComponent theTableTopComponent, MoleculeStructureViewerTopComponent theViewerTopComponent) {
            WindowAdapter.getOutputMode().dockInto(theTableTopComponent);
            WindowAdapter.getEditorMode().dockInto(theViewerTopComponent);

            theTableTopComponent.setViewerTopComponent(theViewerTopComponent);
            theViewerTopComponent.setTableComponent(theTableTopComponent);

            theTableTopComponent.open();
            theViewerTopComponent.open();

            theTableTopComponent.requestActive();
            theViewerTopComponent.requestActive();
        }
    }

    private class ExitButtonActionListener implements ActionListener {

        private PDBImportFrame itsFrame;

        public ExitButtonActionListener(PDBImportFrame itsFrame) {
            this.itsFrame = itsFrame;
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            this.itsFrame.dispose();
        }
    }

    private class PdbIdTextFieldActionListener extends KeyAdapter {

        private PDBImportFrame itsFrame;

        public PdbIdTextFieldActionListener(PDBImportFrame itsFrame) {
            this.itsFrame = itsFrame;
        }

        @Override
        public void keyReleased(KeyEvent ke) {
            if (ke.getKeyCode() == KeyEvent.VK_ENTER) {
                this.itsFrame.getOpenButton().getActionListeners()[0].actionPerformed(null);
            } else if (ke.getKeyCode() == KeyEvent.VK_ESCAPE) {
                this.itsFrame.dispose();
            } else {
                String thePdbId = this.itsFrame.getPdbIdTextField().getText();

                this.itsFrame.getUrlTextField().setText(PDBImporter.URL_HEADER + thePdbId.toUpperCase() + PDBImporter.URL_TAIL);
                this.itsFrame.revalidate();
            }
        }
    }
}
